openapi: "3.0.1"
info:
  title: "smartparkingauthapi"
  version: "2018-05-24T17:52:00Z"
servers:
- url: "https://93e4gv1j2g.execute-api.us-east-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/dev"
paths:
  /queryParking/{proxy+}:
    options:
      parameters:
      - name: "proxy"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestSchema"
        required: true
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSchema"
  /getParkingActivity:
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    x-amazon-apigateway-any-method:
      parameters:
      - name: "ts1"
        in: "query"
        description: "timestamp (larger) between which activity info is requried"
        schema:
          type: "string"
      - name: "deviceID"
        in: "query"
        description: "deviceID of parking meter whose activity info is required"
        schema:
          type: "string"
      - name: "ts2"
        in: "query"
        description: "timestamp (smaller) between which activity info is requried"
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestSchema"
        required: true
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSchema"
  /getParkingActivity/{proxy+}:
    options:
      parameters:
      - name: "proxy"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
        required: true
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestSchema"
        required: true
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSchema"
  /queryParking:
    options:
      responses:
        "200":
          description: "200 response"
          headers:
            Access-Control-Allow-Origin:
              schema:
                type: "string"
            Access-Control-Allow-Methods:
              schema:
                type: "string"
            Access-Control-Allow-Headers:
              schema:
                type: "string"
          content: {}
    x-amazon-apigateway-any-method:
      parameters:
      - name: "longitude"
        in: "query"
        description: "Longitude Value of motorist geolocation"
        schema:
          type: "string"
      - name: "radius"
        in: "query"
        description: "radius in meters around which open parkings are required"
        schema:
          type: "string"
      - name: "latitude"
        in: "query"
        description: "Latitude value of motorist geolocation"
        schema:
          type: "string"
      - name: "Authorization"
        in: "header"
        schema:
          type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestSchema"
        required: true
      responses:
        "200":
          description: "200 response"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseSchema"
components:
  schemas:
    RequestSchema:
      title: "Request Schema"
      required:
      - "request"
      type: "object"
      properties:
        request:
          type: "string"
    ResponseSchema:
      title: "Response Schema"
      required:
      - "response"
      type: "object"
      properties:
        response:
          type: "string"
